# Generated by Django 4.2.5 on 2023-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='shop/Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Publish_date',
            field=models.DateField(default='', verbose_name='Publish Date'),
        ),
    ]
